yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
handler500 = 'core.views.internal_server'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name="Текст",
        help_text="Текст нового поста",
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Дата публикации",
        help_text="Дата публикации поста",
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name="Автор",
        help_text="Автор поста",
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name="posts",
        verbose_name="Группа",
        help_text="Группа, к которой будет относиться пост",
    )
    image = models.ImageField(
        verbose_name='Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name="comments",
        verbose_name="Комментарий",
        help_text="Комментарий к посту",
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name="Автор",
        help_text="Автор комментария",
    )
    text = models.TextField(
        verbose_name="Текст",
        help_text="Текст нового комментария",
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Дата публикации",
        help_text="Дата публикации комментария",
    )

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name="Подписчик",
        help_text="Подписчик на автора",
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name="Автор",
        help_text="Автор постов",
    )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'
        
        constraints = [
            models.UniqueConstraint(
                fields=["user", "author"], name="already_following"
            ),
            models.CheckConstraint(
                check=~models.Q(author=models.F("user")),
                name="not_self_follow"
            )
        ]

yatube/posts/forms.py
from django.forms import ModelForm

from .models import Comment, Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ["text", "group", "image"]


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ["text"]

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db import IntegrityError
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User

POSTS_AMOUNT = 10


@cache_page(20, key_prefix="index_page")
def index(request):
    posts = Post.objects.all()
    page_obj = paginate_posts(request, posts)
    template = 'posts/index.html'

    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group_list.html'

    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    page_obj = paginate_posts(request, posts)

    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    template = 'posts/profile.html'

    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    posts_amount = author.posts.count()

    page_obj = paginate_posts(request, posts)
    following = False
    if request.user.is_authenticated:
        following = (Follow.objects.filter(
            user=request.user,
            author=User.objects.filter(username=username)[0]).exists)
    context = {
        'page_obj': page_obj,
        'author': author,
        'posts_amount': posts_amount,
        'following': following,
    }
    return render(request, template, context)


def paginate_posts(request, posts):
    paginator = Paginator(posts, POSTS_AMOUNT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return page_obj


def post_detail(request, post_id):
    template = 'posts/post_detail.html'

    post = get_object_or_404(Post, pk=post_id)
    post_title = post.text[:30]
    post_pub_date = post.pub_date
    author = post.author
    author_posts_amount = author.posts.all().count()
    comment_form = CommentForm(request.POST or None)
    post_comments = post.comments.all()

    context = {
        "post": post,
        "post_title": post_title,
        "pub_date": post_pub_date,
        "author": author,
        "author_posts_amount": author_posts_amount,
        "comment_form": comment_form,
        "comments": post_comments,
    }

    return render(request, template, context)


@login_required
def post_create(request):

    template = "posts/create_post.html"
    form = PostForm(
        request.POST or None,
        files=request.FILES or None)

    if request.method == 'POST':
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect("posts:profile", post.author)

    context = {
        "form": form,
    }
    return render(request, template, context)


@login_required
def post_edit(request, post_id):

    template = "posts/create_post.html"

    is_edit = True
    post = get_object_or_404(Post, pk=post_id)
    author = post.author
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )

    if request.user == author:
        if request.method == "POST" and form.is_valid:
            post = form.save()
            return redirect("posts:post_detail", post_id)

        context = {
            "is_edit": is_edit,
            "form": form,
        }

        return render(request, template, context)
    return redirect("posts:post_detail", post_id)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    authors = Follow.objects.filter(user=request.user)
    posts = []
    for note in authors:
        posts.extend(Post.objects.filter(author=note.author))
    page_obj = paginate_posts(request, posts)
    template = 'posts/follow.html'

    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    redirect_page = reverse('posts:profile', kwargs={'username': username})
    try:
        Follow.objects.create(
            user=request.user,
            author=User.objects.filter(username=username)[0]
        )
    except IntegrityError:
        return redirect(redirect_page)
    return redirect(redirect_page)


@login_required
def profile_unfollow(request, username):
    Follow.objects.filter(
        user=request.user,
        author=User.objects.filter(username=username)[0]
    ).delete()
    print(
        Follow.objects.filter(
            user=request.user,
            author=User.objects.filter(username=username)[0]
        )
    )
    redirect_page = reverse('posts:profile', kwargs={'username': username})
    return redirect(redirect_page)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
  {% if is_edit %}
    Редактировать запись
  {% else %}
    Добавить запись
  {% endif %} 
{% endblock %} 
{% block content %}
{% load user_filters %}
<main>
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %}
              Редактировать пост
            {% else %}
              Новый пост
            {% endif %}
          </div>
          <div class="card-body">
            <form method="post" enctype="multipart/form-data"
            href="{% url 'posts:post_create' %}">
              {% csrf_token %}
              {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{field.label}}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>
                {{ field|addclass:'form-control' }}
                  {% if field.help_text %}
                    <small id="id_text-help" class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
              </div>
              {% endfor %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %} 
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

yatube/templates/posts/follow.html
<!-- templates/posts/follow.html -->
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Последние обновления ваших авторов
{% endblock %} 
{% block content %}
  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
    <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text }}</p>    
    {% if post.group %}  
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
<!-- templates/posts/index.html -->
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Записи сообщества {{ group.title }}{% endblock %} 
{% block content %}
  <h1>{{ group.title }}</h1>
  <p>{{ group.description }}</p>
  {% for post in page_obj %}
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text }}</p>
    {% if post.group %} 
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %} 

yatube/templates/posts/index.html
<!-- templates/posts/index.html -->
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Последние обновления на сайте
{% endblock %} 
{% block content %}
  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
    <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text }}</p>    
    {% if post.group %}  
      <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы</a>
    {% endif %}
    <p><a href="{% url 'posts:post_detail' post.pk %}">Перейти к посту</a></p>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Пост {{ post_title }}{% endblock %}
{% block content %}
<main>
    <div class="row">
    <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
        <li class="list-group-item">
            Дата публикации: {{ pub_date|date:"d E Y" }}
        </li>
        {% if post.group %}     
            <li class="list-group-item">
                Группа: {{ post.group.title }}
                <a href="{% url 'posts:group_list' post.group.slug %}">
                все записи группы
                </a>
        {% endif %}
        </li>
        <li class="list-group-item">
            Автор: {{ author.get_full_name }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора:  <span >{{ author_posts_amount }}</span>
        </li>
        <li class="list-group-item">
            <a href="{% url 'posts:profile' post.author %}">
            все посты пользователя
            </a>
        </li>
        </ul>
    </aside>
    <article class="col-12 col-md-9">
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
            {{ post.text }} 
        </p>
    </article>
    {% load user_filters %}
    {% if user.is_authenticated %}
    <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
        <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
            {{ comment_form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
        </form>
    </div>
    </div>
    {% endif %}

    {% for comment in comments %}
    <div class="media mb-4">
    <div class="media-body">
        <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
            {{ comment.author.username }}
        </a>
        </h5>
        <p>
        {{ comment.text }}
        </p>
    </div>
    </div>
    {% endfor %} 
</main>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}Профайл пользователя {{ author }}{% endblock %}
{% block content %}
<main>
    <div class="container py-5">     
        <div class="mb-5">  
            <h1>Все посты пользователя {{ author }} </h1>
            <h3>Всего постов: {{ posts_amount }} </h3>
            {% if request.user != author %}
                {% if following %}
                    <a
                    class="btn btn-lg btn-light"
                    href="{% url 'posts:profile_unfollow' author.username %}" role="button"
                    >
                    Отписаться
                    </a>
                {% else %}
                    <a
                        class="btn btn-lg btn-primary"
                        href="{% url 'posts:profile_follow' author.username %}" role="button"
                    >
                        Подписаться
                    </a>
                {% endif %}
            {% endif %}
        </div>
      <article>
        {% for post in page_obj %}
            <ul>
            <li>
                Автор: {{ post.author.get_full_name }}
                <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
            </li>
            <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
            </ul>
            <p>
                {{ post.text }}
            </p>
            <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
            </article>
            <br>
            {% if post.group %}     
                <a href=" {% url 'posts:group_list' post.group.slug %} ">все записи группы</a>        
            {% endif %}
            {% if not forloop.last %}
                <hr>
            {% endif %}
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}
    </div>
</main>
{% endblock %}